name: Fork with Custom .tex Filtering

on:
  workflow_dispatch:  # дозволяє запуск вручну з вкладки Actions

jobs:
  filter-and-commit:
    runs-on: ubuntu-latest

    env:
      SRC_REPO: IlyaCk/statementsToConvert
      DST_REPO: MaltsevVlas1124/statementsToConvert-fork
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      SPECIAL_TEX_DIR: OlympiadsTheirselves/LaTeX # Шлях до спеціальної папки

    steps:
    - name: Checkout destination repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.DST_REPO }}
        token: ${{ env.GITHUB_TOKEN }}
        path: dest

    - name: Clone source repo
      run: |
        git clone https://github.com/${SRC_REPO}.git source

    - name: Filter files
      run: |
        echo "Starting file filtering..."
        FILTERED_DIR="$PWD/filtered" # Абсолютний шлях до папки filtered
        SOURCE_DIR="$PWD/source"     # Абсолютний шлях до папки source
        echo "Filtered directory: $FILTERED_DIR"
        echo "Source directory: $SOURCE_DIR"

        mkdir -p "$FILTERED_DIR"
        cd "$SOURCE_DIR" # Переходимо в source один раз

        # --- Крок 1: Копіюємо всі файли, крім .tex ---
        echo "Copying non-.tex files..."
        find . -type f ! -name "*.tex" -not -path "./.git/*" | while IFS= read -r file; do
          relative_path="${file#./}"
          target_path="$FILTERED_DIR/$relative_path"
          echo "  Copying non-tex: $relative_path to $target_path"
          mkdir -p "$(dirname "$target_path")"
          cp --verbose "$relative_path" "$target_path"
        done

        # --- Крок 2: Копіюємо .tex файли ПОЗА спеціальною папкою (з фільтром парних індексів) ---
        echo "Processing .tex files outside $SPECIAL_TEX_DIR with even-index logic..."
        mapfile -t tex_files_outside < <(find . -type f -name "*.tex" -not -path "./$SPECIAL_TEX_DIR/*" -not -path "./.git/*" | sort)
        i=0
        for file in "${tex_files_outside[@]}"; do
          relative_path="${file#./}"
          if [ $((i % 2)) -eq 0 ]; then
            target_path="$FILTERED_DIR/$relative_path"
            echo "  Copying even index $i (outside): $relative_path to $target_path"
            mkdir -p "$(dirname "$target_path")"
            cp --verbose "$relative_path" "$target_path"
          fi
          i=$((i + 1))
        done

        # --- Крок 3: Обробка спеціальної папки $SPECIAL_TEX_DIR (логіка A/C пар + головний файл) ---
        special_src_dir="$SOURCE_DIR/$SPECIAL_TEX_DIR"
        special_target_dir="$FILTERED_DIR/$SPECIAL_TEX_DIR"
        echo "Processing special directory: $special_src_dir"
        echo "Target directory for special files: $special_target_dir"

        if [ -d "$special_src_dir" ]; then
          mkdir -p "$special_target_dir" # Створюємо цільову папку заздалегідь

          # Знаходимо унікальні базові префікси всередині спеціальної папки
          mapfile -t base_prefixes < <(find "$special_src_dir" -maxdepth 1 -name '*-*-statement.tex' -printf '%f\n' | sed -E 's/^(.*)-[A-Za-z0-9]+-statement\.tex$/\1/' | sort -u)
          echo "  Found potential base prefixes: ${base_prefixes[*]}"

          for base_prefix in "${base_prefixes[@]}"; do
            echo "  Processing prefix: [$base_prefix]"

            # 3а. Копіюємо головний файл (якщо існує)
            main_file_src="$special_src_dir/${base_prefix}.tex"
            echo "    Checking for main file: [$main_file_src]"
            if [ -f "$main_file_src" ]; then
              echo "      Found main file. Attempting verbose copy to $special_target_dir/ ..."
              cp --verbose "$main_file_src" "$special_target_dir/"
              echo "      Main file copy attempted."
            else
              echo "      Main file [$main_file_src] not found."
            fi

            # 3б. Знаходимо та сортуємо ідентифікатори (A, B, C...)
            # Шукаємо файли безпосередньо у special_src_dir
            mapfile -t identifiers < <(find "$special_src_dir" -maxdepth 1 -name "${base_prefix}-*-statement.tex" -printf '%f\n' | sed -E "s/^${base_prefix}-(.+)-statement\.tex$/\1/" | sort)
            echo "    Found identifiers for $base_prefix: [${identifiers[*]}] (Count: ${#identifiers[@]})"

            if [ ${#identifiers[@]} -eq 0 ]; then
              echo "    No statement/tutorial pairs found based on statement files for $base_prefix"
              continue
            fi

            # 3в. Вибираємо та копіюємо пари за індексами 0 (A) та 2 (C)
            indices_to_copy=(0 2) # 0-й (A) та 2-й (C) індекси
            for index in "${indices_to_copy[@]}"; do
              echo "    Checking index: $index"
              if [ "$index" -lt "${#identifiers[@]}" ]; then
                identifier="${identifiers[$index]}"
                echo "      Identifier at index $index: [$identifier]"
                statement_file_src="$special_src_dir/${base_prefix}-${identifier}-statement.tex"
                tutorial_file_src="$special_src_dir/${base_prefix}-${identifier}-tutorial.tex"

                # Копіюємо statement файл, якщо існує
                echo "      Checking for statement file: [$statement_file_src]"
                if [ -f "$statement_file_src" ]; then
                   echo "        Found statement file. Attempting verbose copy to $special_target_dir/ ..."
                   cp --verbose "$statement_file_src" "$special_target_dir/"
                   echo "        Statement file copy attempted."
                else
                   echo "        Statement file [$statement_file_src] not found."
                fi

                # Копіюємо tutorial файл, якщо існує
                 echo "      Checking for tutorial file: [$tutorial_file_src]"
                 if [ -f "$tutorial_file_src" ]; then
                   echo "        Found tutorial file. Attempting verbose copy to $special_target_dir/ ..."
                   cp --verbose "$tutorial_file_src" "$special_target_dir/"
                   echo "        Tutorial file copy attempted."
                 else
                   echo "        Tutorial file [$tutorial_file_src] not found."
                 fi
              else
                 echo "      Index $index is out of bounds for prefix $base_prefix (found ${#identifiers[@]} identifiers)."
              fi
            done # кінець циклу по індексах
          done # кінець циклу по префіксах
        else
          echo "Warning: Special source directory [$special_src_dir] not found."
        fi

        # Немає потреби повертатися, бо ми не робили cd в спеціальну папку
        echo "File filtering finished. Current directory: $PWD" # Має бути $SOURCE_DIR

    - name: Move filtered files into destination repo
      run: |
        echo "Moving filtered files to destination..."
        echo "--- Listing content of filtered directory ($PWD/filtered) ---"
        ls -lR "$PWD/filtered" # Використовуємо абсолютний шлях і рекурсивний лістинг
        echo "--- End of filtered directory listing ---"

        # Використовуємо rsync, АЛЕ виключаємо папку .git з процесу синхронізації/видалення
        # Джерело тепер $PWD/filtered/
        rsync -av --delete --exclude='.git/' "$PWD/filtered/" dest/ || echo "rsync finished with non-critical errors or no changes."

    - name: Commit and push changes to a new branch
      run: |
        cd dest
        echo "Inside dest directory. Current directory: $PWD"
        ls -la # Покажемо вміст, чи є папка .git
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        BRANCH_NAME="original-filtered"
        git checkout -B "$BRANCH_NAME"

        git add .

        if git diff --staged --quiet; then
          echo "Nothing to commit, working tree clean."
        else
          echo "Committing changes..."
          git commit -m "Filtered fork from $SRC_REPO (custom logic for $SPECIAL_TEX_DIR)"
          echo "Pushing changes to $BRANCH_NAME..."
          git push --force origin "$BRANCH_NAME"
        fi
